apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-dev-volumeclaim
  namespace: zabbix-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
