apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  namespace: zabbix-dev
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30008
  selector:
    app: zabbix-web
