apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres-service
  namespace: monitoramento-dev
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
  selector:
    app: zabbix-postgres
