apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres-service
  namespace: zabbix-dev
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 5432
  selector:
    app: zabbix-postgres
