apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-deployment
  namespace: monitoramento-dev
  labels:
    app: zabbix-web
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web-pod
          image: zabbix/zabbix-web-nginx-pgsql
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zabbix-postgres-configmap
            - configMapRef:
                name: zabbix-web-configmap
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
