apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-service
  namespace: zabbix-dev
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 10051
  selector:
    app: zabbix-server
