apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server-deployment
  namespace: monitoramento-dev
  labels:
    app: zabbix-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server-pod
          image: zabbix/zabbix-server-pgsql
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: zabbix-server-configmap
          ports:
            - name: server
              containerPort: 10051
            - name: agent
              containerPort: 10050
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "125m"
      volumes:
        - name: zabbix-server-storage
          persistentVolumeClaim:
            claimName: zabbix-dev-volumeclaim
