apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-service
  namespace: monitoramento-dev
spec:
  ports:
    - name: server
      protocol: TCP
      port: 10051
    - name: agent
      protocol: TCP
      port: 10050
  selector:
    app: zabbix-server
