apiVersion: v1
kind: Service
metadata:
  name: zabbix-snmp-service
  namespace: zabbix-dev
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 1162
  selector:
    app: zabbix-snmp
