apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-mysql-configmap
  namespace: zabbix-dev
data:
  MYSQL_DATABASE: "zabbix"
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zabbix_pwd"
  MYSQL_ROOT_PASSWORD: "root_pwd"
