apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-mysql-deployment
  namespace: zabbix-dev
  labels:
    app: zabbix-mysql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zabbix-mysql
  template:
    metadata:
      labels:
        app: zabbix-mysql
    spec:
      containers:
        - name: zabbix-mysql-pod
          image: mysql
          imagePullPolicy: Always
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8 
            - --collation-server=utf8_bin
          volumeMounts:
            - name: zabbix-mysql-storage
              mountPath: "/var/lib/mysql"
          envFrom:
            - configMapRef:
                name: zabbix-mysql-configmap
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "125m"
      volumes:
        - name: zabbix-mysql-storage
          persistentVolumeClaim:
            claimName: zabbix-dev-volumeclaim
