apiVersion: v1
kind: Service
metadata:
  name: zabbix-mysql-service
  namespace: zabbix-dev
spec:
  type: NodePort
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    app: zabbix-mysql
