apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoramento-dev-volumeclaim
  namespace: monitoramento-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
