apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-gateway-deployment
  namespace: monitoramento-dev
  labels:
    app: zabbix-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zabbix-gateway
  template:
    metadata:
      labels:
        app: zabbix-gateway
    spec:
      containers:
        - name: zabbix-gateway-pod
          image: zabbix/zabbix-java-gateway
          imagePullPolicy: Always
          ports:
            - name: gateway
              containerPort: 10052
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "125m"
