version: '3.9'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    restart: unless-stopped
    volumes:
      - /etc/grafana:/var/lib/grafana
    networks:
      - grafana
    ports:
      - 3000:3000
    

networks:
  grafana:
    name: grafana
    driver: bridge
